version: '3'

services:

  php-server:
    image: php:7.4-fpm-alpine3.15
    container_name: php-server
    networks:
      - php-net
    volumes:
      - ./website/:/var/www/html/
    restart: always


  nginx:
    image: nginx:alpine
    container_name: nginx
    networks:
      - php-net
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./website/:/var/www/html/ 
      - ./cert/nginx-certificate.crt:/etc/nginx/ssl/nginx-certificate.crt 
      - ./cert/nginx.key:/etc/nginx/ssl/nginx.key
    ports:
      - 80:80
      - 443:443
    restart: always

networks:
  php-net:

  